// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLSiDSBNGq75eFxZIb1NFH8w9ZI9BhZ9w',
    appId: '1:914421826377:web:e7b3d1a4ece912a90b9098',
    messagingSenderId: '914421826377',
    projectId: 'havakontrol-43eef',
    authDomain: 'havakontrol-43eef.firebaseapp.com',
    databaseURL: 'https://havakontrol-43eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'havakontrol-43eef.appspot.com',
    measurementId: 'G-RNV6XMRMJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYWIiRfL9a2WDWzD9vCx3p2Dljbuhq3U',
    appId: '1:914421826377:android:251184929c2ad9130b9098',
    messagingSenderId: '914421826377',
    projectId: 'havakontrol-43eef',
    databaseURL: 'https://havakontrol-43eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'havakontrol-43eef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZb_YdWpC6lg2mKtpnoBtiBGyb9YX0Ebc',
    appId: '1:914421826377:ios:0d5a7caa49129a6d0b9098',
    messagingSenderId: '914421826377',
    projectId: 'havakontrol-43eef',
    databaseURL: 'https://havakontrol-43eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'havakontrol-43eef.appspot.com',
    iosBundleId: 'com.example.havaKontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZb_YdWpC6lg2mKtpnoBtiBGyb9YX0Ebc',
    appId: '1:914421826377:ios:0d5a7caa49129a6d0b9098',
    messagingSenderId: '914421826377',
    projectId: 'havakontrol-43eef',
    databaseURL: 'https://havakontrol-43eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'havakontrol-43eef.appspot.com',
    iosBundleId: 'com.example.havaKontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLSiDSBNGq75eFxZIb1NFH8w9ZI9BhZ9w',
    appId: '1:914421826377:web:848947e8bfd98f660b9098',
    messagingSenderId: '914421826377',
    projectId: 'havakontrol-43eef',
    authDomain: 'havakontrol-43eef.firebaseapp.com',
    databaseURL: 'https://havakontrol-43eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'havakontrol-43eef.appspot.com',
    measurementId: 'G-B11SM446C0',
  );
}
